import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';


@Component({
  selector: 'app-film',
  templateUrl: './film.component.html',
  styleUrls: ['./film.component.scss']
})
export class FilmComponent implements OnInit{
  searchQuery: string = '';
  

  formGroup: FormGroup;
  
  films: any[] = [
    { title: 'Spider-Man: No Way Home 1', genre: 'Action, Aventure, Fantaisie', director: 'Jon Watts', duration: "2h28m", description: '"Spider-Man: No Way Home" est un film de super-héros qui suit les aventures de Peter Parker / Spider-Man, confronté à une crise lorsque son identité secrète est révélée au grand public. Dans sa quête pour réparer les dommages causés par un sort magique, Peter se retrouve plongé dans un multivers où il rencontre d autres versions de lui-même. Ensemble, ces Spider-Men doivent affronter des super-vilains venus de différentes réalités pour sauver leur univers. Le film est acclamé pour son action palpitante, ses performances captivantes et son hommage nostalgique à l héritage de Spider-Man au cinéma.', imageUrl: 'assets/Spiderman.png' },
    { title: 'The Batman', genre: 'Action, Crime, Drame', director: 'Matt Reeves', duration: "2h56m", description: '"The Batman" est un film de super-héros qui explore une version sombre et réaliste de l univers de Batman. Réalisé par Matt Reeves, il met en vedette Robert Pattinson dans le rôle de Bruce Wayne / Batman. L intrigue suit Batman alors qu il enquête sur une série de meurtres mystérieux à Gotham City, révélant une conspiration impliquant certains des criminels les plus redoutables de la ville, y compris le légendaire Joker. Le film offre une plongée profonde dans l esprit torturé de Bruce Wayne alors qu il lutte contre ses propres démons intérieurs tout en tentant de protéger sa ville de la corruption et de la criminalité. Avec une atmosphère sombre et une intrigue captivante, The Batman promet d être une expérience cinématographique intense et immersive pour les fans du justicier masqué et les amateurs de films de super-héros en général.' ,imageUrl: 'assets/The Batman.png' },
    { title: 'Dune', genre: 'Science-fiction, Aventure, Action', director: 'Denis Villeneuve', duration: "2h35m", description: '"Dune" est une épopée de science-fiction réalisée par Denis Villeneuve, adaptée du roman du même nom écrit par Frank Herbert. Le film suit l histoire de Paul Atreides, un jeune noble dont la famille est chargée de gouverner la planète désertique Arrakis, connue pour sa ressource la plus précieuse, le "melange d épices". Alors que Paul découvre son destin en tant que prophète mystique, il se retrouve impliqué dans un conflit politique et une lutte pour le contrôle de la planète et de ses ressources. Avec des paysages désertiques époustouflants, une intrigue complexe et des performances remarquables de la part de son casting, "Dune" offre une expérience cinématographique immersive et captivante pour les amateurs de science-fiction.' , imageUrl: 'assets/Dune.png' },

    { title: 'Venom: Let There Be Carnage', genre: 'Action, Aventure, Science-Fiction', director: 'Andy Serkis', duration: "1h37m", description: '"Venom: Let There Be Carnage" est un film de super-héros réalisé par Andy Serkis, basé sur le personnage de Venom de Marvel Comics. Dans cette suite tant attendue, Eddie Brock (joué par Tom Hardy) tente de coexister avec le symbiote alien Venom, qui habite son corps, tout en jonglant avec les hauts et les bas de leur relation. Cependant, leur existence tranquille est perturbée par l apparition de Cletus Kasady (joué par Woody Harrelson), un tueur en série qui fusionne avec un symbiote extrêmement puissant appelé Carnage.Alors que Venom et Carnage s affrontent dans un combat titanesque, Eddie doit trouver un moyen de contenir cette nouvelle menace tout en gérant les défis personnels et interpersonnels qui lui sont propres. Entre les scènes d action explosives et l humour caractéristique de la franchise, "Venom: Let There Be Carnage" offre une aventure divertissante et chargée en adrénaline pour les fans de comics et les amateurs de films de super-héros.' ,imageUrl: 'assets/Venom.png' },
    { title: 'Man of Steel', genre: 'Action, Aventure, Science-Fiction', director: 'Zack Snyder', duration: "2h23m", description: '"Man of Steel" est un film de super-héros qui explore les origines emblématiques de l un des personnages les plus légendaires de l histoire des comics, Superman. Réalisé par Zack Snyder, le film suit le voyage de Clark Kent / Superman, interprété par Henry Cavill, depuis son enfance sur la planète Krypton jusqu à son arrivée sur Terre, où il découvre ses pouvoirs surhumains.Alors que Clark tente de trouver sa place dans le monde en tant que héros, il doit affronter son passé et accepter sa destinée de protéger l humanité contre les menaces qui pèsent sur elle. Parmi ces menaces se trouve le Général Zod, un Kryptonien exilé qui cherche à conquérir la Terre et à reconstruire leur civilisation déchue.Avec des scènes d action spectaculaires, des effets spéciaux époustouflants et une exploration approfondie du personnage de Superman, "Man of Steel" offre une interprétation moderne et captivante du mythe du super-héros. Il établit également le ton pour le DC Extended Universe, ou DCEU, qui explore davantage l univers cinématographique des super-héros de DC Comics.' ,imageUrl: 'assets/ManOfSteel.png' },
    { title: 'Joker', genre: 'Drame, Thriller, Crime', director: 'Todd Phillips', duration: "2h2m", description: '"Joker" est un film dramatique de 2019 réalisé par Todd Phillips, qui propose une relecture sombre et psychologique de l origine du célèbre ennemi de Batman, le Joker. Le film met en vedette Joaquin Phoenix dans le rôle principal d Arthur Fleck, un comédien de stand-up raté vivant dans la Gotham City des années 1980, une ville en proie à la pauvreté, à la criminalité et à la corruption.Arthur, un homme souffrant de troubles mentaux et de traumatismes émotionnels, bascule peu à peu dans la folie alors qu il est marginalisé et maltraité par la société. Ses frustrations et ses douleurs intérieures le conduisent à embrasser progressivement une identité de clown criminel, le Joker, déclenchant ainsi une série d événements chaotiques et violents qui bouleversent Gotham City.Porté par une performance magistrale de Joaquin Phoenix, "Joker" offre une étude de caractère profonde et dérangeante sur la descente aux enfers d un homme brisé, ainsi qu une méditation sombre sur la nature de la société et sur la manière dont elle traite les individus marginalisés. Le film a été acclamé par la critique pour sa mise en scène, son scénario complexe et sa capacité à susciter la réflexion sur des thèmes sociaux et psychologiques pertinents.' ,imageUrl: 'assets/Joker.png' },

    { title: 'Aquaman et le royaume perdu', genre: 'Action, Aventure, Fantaisie', director: 'James Wan', duration: "Inconnu", description: '"Aquaman et le royaume perdu" est un film de super-héros basé sur le personnage de DC Comics, Aquaman. Réalisé par James Wan, il est la suite du film à succès "Aquaman" sorti en 2018. Le film met en vedette Jason Momoa dans le rôle d Arthur Curry / Aquaman, un héros mi-homme mi-atlante, et Amber Heard dans le rôle de Mera, son alliée.L histoire suit Arthur et Mera alors qu ils se lancent dans une quête périlleuse pour retrouver le légendaire royaume perdu de l Atlantide, en espérant y découvrir des réponses sur le passé mystérieux d Arthur et sur la menace imminente qui pèse sur le monde sous-marin. Cependant, leur voyage est compliqué par de nouveaux ennemis redoutables et des défis inattendus qui mettent à l épreuve leur courage et leur loyauté."Aquaman et le royaume perdu" promet d offrir aux fans une aventure épique remplie d action sous-marine, de paysages spectaculaires et de personnages mythiques. Avec des effets spéciaux de pointe et une histoire captivante, le film promet de plonger les spectateurs dans un monde fantastique rempli de magie, de mystère et d intrigue.' ,imageUrl: 'assets/Aquaman.png' },
    { title: 'The Flash', genre: 'Action, Aventure', director: 'Andy Muschietti', duration: "Inconnu", description: '"The Flash" est un prochain film de super-héros basé sur le personnage de DC Comics du même nom. Réalisé par Andy Muschietti, le film mettra en vedette Ezra Miller reprenant son rôle de Barry Allen / The Flash, un super-héros possédant la capacité de se déplacer à des vitesses surhumaines.L intrigue du film explorera le concept du multivers, où différentes réalités parallèles coexistent. Barry Allen se retrouve confronté à une crise qui menace l équilibre des réalités, et il doit voyager à travers les différentes dimensions pour trouver une solution et sauver l univers.Avec des éléments de voyage dans le temps, d action palpitante et d aventure interdimensionnelle, "The Flash" promet d offrir aux fans une expérience cinématographique épique et captivante. Le film devrait également présenter une distribution de personnages emblématiques de l univers DC Comics, ajoutant une dimension supplémentaire à l histoire et à l univers cinématographique de DC.' ,imageUrl: 'assets/Flash.png' },
    { title: 'Black Adam', genre: 'Science-fiction, Aventure, Action', director: 'Jaume Collet-Serra', duration: "Inconnu", description: '"Black Adam" est un film de super-héros basé sur le personnage de DC Comics du même nom. Réalisé par Jaume Collet-Serra, le film mettra en vedette Dwayne "The Rock" Johnson dans le rôle principal de Black Adam, un anti-héros doté de pouvoirs magiques et physiques extraordinaires.L intrigue du film explorera les origines et les motivations de Black Adam, un ancien champion égyptien doté de pouvoirs issus de dieux antiques. Après avoir été emprisonné pendant des millénaires, Black Adam est libéré dans le monde moderne et cherche à établir sa propre vision de la justice, même si cela signifie affronter d autres héros et vilains de l univers DC.Avec Dwayne Johnson apportant sa présence imposante et son charisme à ce rôle, "Black Adam" promet d être un film rempli d action, d aventure et de spectaculaire, tout en explorant les thèmes complexes de la responsabilité, du pouvoir et de la moralité. Le film devrait également étendre l univers cinématographique de DC en introduisant de nouveaux personnages et en élargissant les horizons de l univers des super-héros.' ,imageUrl: 'assets/BlackAdam.png' }




  ];

  constructor() {
    
    this.formGroup = new FormGroup({
  });
  }

  ngOnInit(): void {
   
}

}
